development:
    dialect: postgres
    datasource: dbname=aws_services sslmode=disable
    dir: db/migrations
    table: migrations

production:
    dialect: postgres
    datasource: dbname=aws_services sslmode=disable
    dir: db/migrations
    table: migrations
